name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Install
        run: |
          brew tap liquidaty/zsv
          brew install zsv
      
      - name: Check installed version
        run: |
          zsv version

      - name: Uninstall
        run: |
          brew uninstall zsv
          zsv version || true
